### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by jatin-labs** [vikramshinde12/document-ai-in-gcp#2]
![image](https://user-images.githubusercontent.com/34629705/126076290-4f40e069-9a68-4b33-902a-290683533bd2.png)
![Screenshot 2021-07-18 224716](https://user-images.githubusercontent.com/34629705/126076315-88535411-30d6-477b-9f8e-27070aeadc8f.png)

**Comment by jatin-labs** [comment]
The GCR image creation script for the service is mentioned here.
https://github.com/vikramshinde12/document-ai-in-gcp/tree/master/service

**Comment by dtcyad1** [comment]
Hi Vikram,

Great Tutorial. However, I am facing the same issue as described here. This is what i did. I went to the front-app folder and followed the instructions there. That gets my front end up and running. Then i come back to terraform folder and now follow the instruction there - but making 2 changes - i switch the front-app and restapi to my project. However, when i run the apply - it has issues with the frontend-app and the restapi - , 

google_cloud_run_service.front-end: Still creating... [5m20s elapsed]
google_cloud_run_service.front-end: Still creating... [5m30s elapsed]
google_cloud_run_service.front-end: Still creating... [5m40s elapsed]
google_cloud_run_service.front-end: Still creating... [5m50s elapsed]
╷
│ Error: Error creating Service: googleapi: Error 409: Resource 'frontend-app' already exists.
│ 
│   with google_cloud_run_service.front-end,
│   on main.tf line 102, in resource "google_cloud_run_service" "front-end":
│  102: resource "google_cloud_run_service" "front-end" {
│ 
╵
╷
│ Error: Error waiting to create Service: resource is in failed state "Ready:False", message: Image 'gcr.io/terraform-cloudsearch-docai/restapi' not found.
│ 
│   with google_cloud_run_service.restapi,
│   on main.tf line 133, in resource "google_cloud_run_service" "restapi":
│  133: resource "google_cloud_run_service" "restapi" {

What am i missing?
Thanks
